### ISSUE TITLE
[Bug] v0.3.3 Crash when trying to create slab subtypes (again)

### ISSUE THREAD

**Issue by Titus-Armillius** [cubex2/customstuff4#13] opened 2017-06-20 03:40 UTC
The same crash happens with the latest version, any ideas why?

Crash Report: https://pastebin.com/07s51V38

Json: https://pastebin.com/HjyxX6Bg

I even tried deleting and reloading the custom_assets.class file, but that didn't work.

**Comment by cubex2** [comment] 2017-06-20 08:22
This is not the cause of the crash but the entry for the slab should look like this:
```json
{
  "id": "blocka_slab",
  "creativeTab": "materials",
  "material": "ground",
  "itemModel": "custom_assets:blocka_slab",
  "drop": "minecraft:air",
  "doubleSlab": {
    "block": "custom_assets:blocka"
  }
}
```

I've uploaded a fix for this.

**Closed by cubex2** 2017-06-20 08:22 UTC

**Comment by Titus-Armillius** [comment] 2017-06-20 09:17
@cubex2 I just tried v0.3.4 and this time the crash has changed.

Crash report: https://pastebin.com/zvJU7K4A

Json: https://pastebin.com/qMEMzq3E

**Comment by cubex2** [comment] 2017-06-20 12:09
Your slab still uses the doubleSlab attribute wrong. You have a whole new slab with just the doubleSlab attribute and no id which causes the crash.
